name: exposing
dependencies:
  - python=3.8
  - pytorch::pytorch=1.7.1
  - cudatoolkit=10.2
  - pip
  - conda-forge::spacy=2.3.2
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
    - transformers==4.4.0
    - scispacy==0.2.5
    - tqdm
    - gensim==3.8.0
    - swifter==1.0.7
